apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urbanlift
resources:
  - namespace.yaml
  - infra/mysql.yaml
  - infra/redis.yaml
  - apps/booking.yaml
  - apps/socket-kafka.yaml
