spring:
  application:
    name: Uber-SocketKafkaService

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/uber_db_local
    username: root
    password: root

server:
  port: 3002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true